project_id = "clgwzbxmjmxktwreubqc"

[functions.analyze-spending]
verify_jwt = false

[functions.data-export]
verify_jwt = false

[functions.parse-receipt]
verify_jwt = true

[functions.categorize-shopping-item]
verify_jwt = true
